### ISSUE TITLE
Can not load orebfuscator

### ISSUE THREAD

**Issue by MrCrab7** [Imprex-Development/orebfuscator#272] opened 2023-03-06 17:03 UTC
### Description

Server just can not load orebfuscator

### Reproduction Steps

loaded oredfuscator
loaded ProtocolLib
unzipped oredfuscator
unzipped ProtocolLib
 
turned the server on

joined the server with the x-ray, but x-ray was still working 

### Expected Behaviour

i espected a working plugin

### Server Details

3661-Spigot-19641c7-8434e36 (MC: 1.19.3)

### Orebfuscator Version

5.3.2

### ProtocolLib Version

4.8

### Logs and Configs

Error occurred (in the plugin loader) while disabling Orebfuscator v5.3.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.config.OrebfuscatorConfig.proximityEnabled()" because "this.config" is null

### Extra Details

Error occurred while enabling Orebfuscator v5.3.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/accessors/Accessors
        at net.imprex.orebfuscator.util.HeightAccessor.getWorldMethod0(HeightAccessor.java:38) ~[?:?]
        at net.imprex.orebfuscator.util.HeightAccessor.getWorldMethod(HeightAccessor.java:26) ~[?:?]
        at net.imprex.orebfuscator.util.HeightAccessor.<clinit>(HeightAccessor.java:21) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig$OrebfuscatorWorldConfigBundle.<init>(OrebfuscatorConfig.java:308) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.deserialize(OrebfuscatorConfig.java:161) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:58) ~[?:?]
        at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:52) ~[?:?]
        at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:47) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3661-Spigot-19641c7-8434e36]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.reflect.accessors.Accessors
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 19 more

**Comment by NgLoader** [comment] 2023-03-06 18:03
Duplicate of #269 

You need to use the latest dev build from Protocollib [Dev Build](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/)

**Closed as not planned by NgLoader** 2023-03-06 18:03 UTC
Labels: bug
