### ISSUE TITLE
On the latest version, you can see ores through non-full blocks 

### ISSUE THREAD

**Issue by ghost** [Imprex-Development/orebfuscator#148] opened 2021-12-02 17:01 UTC
On the latest version of orebfuscator on 1.18, you can see the ores used to block xray through the corner of stairs
![image](https://user-images.githubusercontent.com/72661987/144468320-9d2a485f-ed1f-4be7-8fbd-e65ac7936437.png)

**Comment by ToastedEggplant** [comment] 2021-12-02 17:39
Ah, I was writing up my issue at the same time this was posted, nice.

**Comment by Ingrim4** [comment] 2021-12-02 21:56
Duplicate of #149

**Closed as completed by Ingrim4** 2021-12-02 21:56 UTC
Labels: bug, duplicate
