### ISSUE TITLE
orebfuscator didnt work, please help

### ISSUE THREAD

**Issue by MathReif** [Imprex-Development/orebfuscator#144] opened 2021-12-01 16:22 UTC
[21:30:47] [Server thread/INFO]: [Orebfuscator] Enabling Orebfuscator v5.1.6
[21:30:47] [Server thread/INFO]: [Orebfuscator] HeightAccessor found method: World::getMaxHeight()
[21:30:47] [Server thread/INFO]: [Orebfuscator] HeightAccessor found method: World::getMinHeight()
[21:30:47] [Server thread/ERROR]: [Orebfuscator] An error occurred while enabling plugin
[21:30:47] [Server thread/ERROR]: [Orebfuscator] null
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.nio.file.Files.copy(Files.java:3128) ~[?:?]
	at net.imprex.orebfuscator.config.OrebfuscatorConfig.createConfigIfNotExist(OrebfuscatorConfig.java:82) ~[?:?]
	at net.imprex.orebfuscator.config.OrebfuscatorConfig.load(OrebfuscatorConfig.java:53) ~[?:?]
	at net.imprex.orebfuscator.config.OrebfuscatorConfig.<init>(OrebfuscatorConfig.java:49) ~[?:?]
	at net.imprex.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:611) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:993) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[21:30:47] [Server thread/INFO]: [Orebfuscator] Disabling Orebfuscator v5.1.6
[21:30:47] [Server thread/ERROR]: Error occurred while disabling Orebfuscator v5.1.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.imprex.orebfuscator.cache.ChunkCache.close()" because "this.chunkCache" is null
	at net.imprex.orebfuscator.Orebfuscator.onDisable(Orebfuscator.java:96) ~[?:?]

**Comment by Ingrim4** [comment] 2021-12-01 18:06
We are currently still working on an 1.18 port. (Duplicate of #142)

**Closed as completed by Ingrim4** 2021-12-01 18:06 UTC
Labels: duplicate
