### ISSUE TITLE
Chunks doesn't load cuz of orebfuscator.

### ISSUE THREAD

**Issue by Mcdikmen** [Imprex-Development/orebfuscator#100] opened 2021-03-15 20:21 UTC
Hello,

I have a problem about a chunk load. It's not just about me, cuz all my players are facing this problem. If i remove the orebfuscator plugin, problem is resolving right away.

Waiting your comments.

Here is the video: https://youtu.be/SSziD_OmAhc

Thank u.

Using, ProtocolLib v4.6.1-SNAPSHOT-b498

Using, git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

OFC version 5.1.4

**Comment by Ingrim4** [comment] 2021-03-15 21:42
Could you try to disable the cache and see if that fixes the problem. If that would fix it I would like you to try a special version of OFC which uses the async protocollib listener but not the cache to isolate the problems origin. I hope that you cooperate with me on this since this is a know issue (#60) that I can't reproduce but would like to resolve.

**Comment by MrPranklez** [comment] 2021-06-07 20:42
I also ran into this issue when I join a server, I'll try to disable the cache and see if that resolves it https://i.imgur.com/sGobmHJ.png 

EDIT: Since disabling it things seem to work fine again

**Comment by Ingrim4** [comment] 2021-06-08 17:16
Here is the special version I promised: https://github.com/Imprex-Development/Orebfuscator/suites/2943443220/artifacts/66155718 Source-Code can be found here: https://github.com/Imprex-Development/Orebfuscator/tree/async-protocollib-sync-obfuscation

Could u tell me regardless of the cache options if this version does work for you or if it doesn't.

**Comment by MrPranklez** [comment] 2021-06-17 09:01
It appears to be working from what i've seen using it the past few days

**Comment by Ingrim4** [comment] 2021-06-17 09:38
Are you talking about the special version?

**Comment by 0subzero** [comment] 2021-09-06 18:55
> 
> 
> Here is the special version I promised: https://github.com/Imprex-Development/Orebfuscator/suites/2943443220/artifacts/66155718 Source-Code can be found here: https://github.com/Imprex-Development/Orebfuscator/tree/async-protocollib-sync-obfuscation
> 
> Could u tell me regardless of the cache options if this version does work for you or if it doesn't.

Good day.
Looks like this version just doesn't work on 1.17.1, right? Because it just does nothing :(
yeah, found in the log:

#######################
[20:50:19] [Server thread/INFO]: [Orebfuscator] cache.protocolLibThreads is less than one, choosing processor count as value = 4
[20:50:19] [Server thread/INFO]: [Orebfuscator] Searching NMS adapter for server version "v1_17_R1"!
[20:50:19] [Server thread/ERROR]: [Orebfuscator] An error occurred while enabling plugin
[20:50:19] [Server thread/ERROR]: [Orebfuscator] Server version "v1_17_R1" is currently not supported!
#######################

Is there any solution for 1.17.1 or just disable cache?

**Comment by Ingrim4** [comment] 2021-09-06 22:00
Someone once mentioned disabling the proximity hider would resolve the issue. If you could test that and tell us if that really resolved the issue I would have a starting point to finally fix this.

**Comment by 0subzero** [comment] 2021-09-07 08:32
> 
> 
> Someone once mentioned disabling the proximity hider would resolve the issue. If you could test that and tell us if that really resolved the issue I would have a starting point to finally fix this.

Nope. Can't confirm that.
proximity:
- enabled: false

doesn't help with this problem.

**Comment by Ingrim4** [comment] 2021-09-07 13:50
I will update the "special" version later today when I'm home so you can test it. Also feel free to add me on Discord to discuss this in more detail: Maurice#7519

**Comment by 0subzero** [comment] 2021-09-07 14:03
Can't write to you because we are not "friends" )
you should accept it first from alex

**Comment by Ingrim4** [comment] 2021-12-10 21:47
duplicate of #60

**Closed as completed by Ingrim4** 2021-12-10 21:47 UTC
Labels: bug, duplicate
