### ISSUE TITLE
Every once in a while an error keeps popping up *obfuscating chat* 

### ISSUE THREAD

**Issue by Nicholindo** [Imprex-Development/orebfuscator#238] opened 2022-08-31 03:41 UTC
### Description

every once in a while this error pops up in chat "Error Unable to intercept a read client packet.(javalang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@71d4947f."
![Screenshot_1](https://user-images.githubusercontent.com/66169669/187587335-dd50b25e-2a27-4ca6-97b7-70bdd1b7ba90.png)

### Reproduction Steps

I installed the plugin + the library and started mining and testing using a texture pack and it was working fine until the problem started happening.

### Expected Behaviour

The obfuscator works very well, I even tested it but it does show that message every 1 minute or so

### Server Details

Spigot 1.19

### Orebfuscator Version

5.3.0

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment] 2022-08-31 04:12
Duplicate of #224

**Closed as completed** 2022-08-31 04:13 UTC
Labels: support
