### ISSUE TITLE
I still see ores with xray in every gamemode

### ISSUE THREAD

**Issue by 4kKoZ** [Imprex-Development/orebfuscator#297] opened 2023-06-14 14:38 UTC
### Description

<img width="1089" alt="Screenshot 2023-06-14 at 10 34 39 AM" src="https://github.com/Imprex-Development/orebfuscator/assets/136613764/2a12e742-9363-4d8c-84a6-46d74fad6216">

### Reproduction Steps

[dump-2023-06-14_14.36.42.log](https://github.com/Imprex-Development/orebfuscator/files/11746905/dump-2023-06-14_14.36.42.log)

### Expected Behaviour

i tought that all the stone/deepslate and all ores would be replaced with random visual blocks like diamond ores and stuff everywhere but actually its not yk

### Orebfuscator Dump

[Uploading dump-2023-06-14_14.36.42.json…]()

**Comment by NgLoader** [comment] 2023-06-14 15:47
You need to manuel add your world names into the orebufscation config.

Also check Ingrim4 comment: https://github.com/Imprex-Development/orebfuscator/issues/293#issuecomment-1585730189
duplicate of #293

**Comment by 4kKoZ** [comment] 2023-06-14 16:52
> You need to manuel add your world names into the orebufscation config. Your currently world is named `World` so you need to change these values in your orebufscation config under worlds from `world` to `World`
> 
> Also check Ingrim4 comment: [#293 (comment)](https://github.com/Imprex-Development/orebfuscator/issues/293#issuecomment-1585730189) duplicate of #293

i dont get what i need to put and where in the config 
<img width="365" alt="Screenshot 2023-06-14 at 12 52 47 PM" src="https://github.com/Imprex-Development/orebfuscator/assets/136613764/a158998e-da10-4f10-a375-afbe44a468da">

**Comment by NgLoader** [comment] 2023-06-14 18:29
Just add under the section ``worlds`` your currently world names.
You can find some more information about the configuration [here](https://github.com/Imprex-Development/Orebfuscator/wiki/Config#world-matchers)

![image](https://github.com/Imprex-Development/orebfuscator/assets/13753840/a6bb5f4e-50e6-4a5d-a7c7-27a0a9263785)

**Comment by Ingrim4** [comment] 2023-09-05 15:18
Closed due to inactivity

**Closed as completed by Ingrim4** 2023-09-05 15:18 UTC
Labels: support
