### ISSUE TITLE
Console Error Message in 1.18.1

### ISSUE THREAD

**Issue by TBK818** [Imprex-Development/orebfuscator#163] opened 2021-12-28 18:19 UTC
Hello. I had previously been using this plugin in 1.17 and it worked fine. Now I am attempting to use it in a new 1.18.1 server and every time the server restarts, I receive this error message in console followed by a much longer error: [28.12 13:11:28] [Server] java.lang.NullPointerExceptionCannot invoke "net.imprex.orebfuscator.cache.ChunkCache.close()" because "this.chunkCache" is null. Every time this happens, I have to delete and re install the plugin so it can work again. After that if the server restarts this occurs again. I was wondering if there is a solution to this as this plugin is very useful to my server and has been great in the past.

**Comment by NgLoader** [comment] 2021-12-28 18:53
Please fill out the following [template](https://github.com/Imprex-Development/Orebfuscator/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

Server Version: 
Orebfuscator Version: 
Protocollib Version:

**Comment by TBK818** [comment] 2021-12-28 19:35
Server Version: 1.18.1
Orebfuscator Version: 5.2.1
Protocollib Version: 4.7.0

**Comment by NgLoader** [comment] 2021-12-28 22:13
Can you please provide your complete log?
Please use pastebin.

**Comment by TBK818** [comment] 2021-12-28 22:42
Here is the full error message in console: https://pastebin.com/9zM6Mi9y

**Comment by Ingrim4** [comment] 2021-12-31 12:17
duplicate of #164

**Closed as completed by Ingrim4** 2021-12-31 12:17 UTC
Labels: bug, duplicate
