### ISSUE TITLE
Cache issue causing fake ores on some exposed stone

### ISSUE THREAD

**Issue by xoxfaby** [Imprex-Development/orebfuscator#260] opened 2022-12-29 17:00 UTC
### Description

Some(?) manually exposed surfaces of stone show as obfuscated blocks. It updates correctly when mining near it, but leaving the area and coming back resets it. It's not 100% consistent, some of my earlier mined up areas seem fine as far as I can see, but this surface for example will always do this [(example gif)](https://gfycat.com/BothHelplessHorse). 

As I was collecting the info for this issue I saw the config option for caching and figured it was a cache issue which I confirmed by renaming my cache folder and restarting my server, so it looks like the cache somehow wasn't updated for the fact that I mined that area, and it was also never updated when I triggered the block updates as seen in the issue. Not sure how. 

### Reproduction Steps

Mine up an area of stone so that it leaves a wall of natural stone exposed. 
Leave area. 
Come back.
Stone is replaced with obfuscated blocks.

### Expected Behaviour

Expected behaviour is to see the normal blocks. 

### Server Details

git-Paper-365 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 90750a6)

### Orebfuscator Version

5.3.2

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### Logs and Configs

There was no relevant log output and my config file is barely changed from default but here:

https://gist.github.com/53d71912fda121809b997be6e2961c72

**Comment by Ingrim4** [comment] 2023-01-01 20:53
Duplicate of #255 (needs the same fix as #255)

**Closed as completed by Ingrim4** 2023-01-01 20:53 UTC
Labels: bug, duplicate
