### ISSUE TITLE
Unable to intercept a read client packet 

### ISSUE THREAD

**Issue by SnowS0ng** [Imprex-Development/orebfuscator#232] opened 2022-07-22 07:56 UTC
### Description

I keep getting spammed with a message in chat ever since i added the pluggin
![image](https://user-images.githubusercontent.com/71718836/180391035-805f4e74-8109-4de0-b679-5a6bb0e47812.png)

### Reproduction Steps

Insert orefuscator pluggin into server with protocalLib
Op yourself

### Expected Behaviour

No Chat Spam

### Server Details

This server is running Paper version git-Paper-70 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: d0e7fa4) You are running the latest version Previous version: git-Paper-"036a09c" (MC: 1.19)

### Orebfuscator Version

5.3.0

### ProtocolLib Version

4.8.0

**Comment by NgLoader** [comment] 2022-07-22 20:32
Duplicate of #224

**Closed as completed by NgLoader** 2022-07-22 20:32 UTC
Labels: bug
