### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mieszko581945** [Imprex-Development/orebfuscator#296] opened 2023-06-14 12:03 UTC
### Description

Orebfuscator totally doesn't work. I made everything. Nothing work. Ores are visible on all gamemodes, for all players.
![Orebfuscator not work](https://github.com/Imprex-Development/orebfuscator/assets/136355592/85487085-b577-466a-9d30-2752f0b89166)

### Reproduction Steps

1. I downloaded to my aternos server this plugin on version 1.20
2. I turned on server
3. I entered on server and enabled x-ray ultimate
4. I see all ores. On every gamemode.

### Expected Behaviour

I thought, that ores will be invisible or obfuscated and in config I will can simple set this.

### Orebfuscator Dump

https://gist.github.com/Mieszko581945/6962fb0ab7c2dfbc8478039845e87818

### Extra Details

In server console there are no errors. He writed me, that orebfuscator is enabled.

**Comment by Mieszko581945** [comment] 2023-06-14 12:06
I think, I made something wrong. But I don,t know what and where.

**Comment by NgLoader** [comment] 2023-06-14 15:44
You need to manuel add your world names into the orebufscation config.

Also check Ingrim4 comment: https://github.com/Imprex-Development/orebfuscator/issues/293#issuecomment-1585730189
duplicate of #293

**Comment by Mieszko581945** [comment] 2023-06-14 17:13
Thanks, very much. One lowercase instead of uppercase in name of world. Now all is working perfectly.

**Closed** 2023-06-14 18:25 UTC
Labels: support
