### ISSUE TITLE
Not working 1.21 please give beta

### ISSUE THREAD

**Issue by PvPAndre** [Imprex-Development/orebfuscator#379] opened 2024-06-17 09:50 UTC
### Description

I tried using the 1.20.6 version of the plugin but its not working, pleaase can you give a link for 1.21, i saw one in another issue request but it was saying 404 page not found.

### Reproduction Steps

Doesnt work in 1.21

### Expected Behaviour

to work in 1.21

### Orebfuscator Dump

dont have it

**Comment by Ingrim4** [comment] 2024-06-17 14:56
Duplicate of #376.

https://github.com/Imprex-Development/orebfuscator/actions/runs/9528215040/artifacts/1604772033

**Closed as completed by Ingrim4** 2024-06-17 14:56 UTC
Labels: bug

**Comment by Nikoroq** [comment] 2024-06-18 16:49
> Duplicate of #376.
> 
> https://github.com/Imprex-Development/orebfuscator/actions/runs/9528215040/artifacts/1604772033

this is exactly what this user mentioned. This link isn't working for those who is not registered on github. Give a mirror in your solution of 376.
